name: vstd

on:
  pull_request:
    branches:
      - main
    paths:
      - docs/**
      - src/**
      - tests/**
      - tooling/**
      - flake.nix
      - flake.lock
      - .github/workflows/flake.yml
      - .clang-format
      - .clang-tidy

concurrency:
  group: pre-merge-checks
  cancel-in-progress: true

jobs:
  flake:
    uses: voidptrr/vtools/.github/workflows/checks.yml@941930869873d6e09056eac013e3b9457b941b3f
